### ISSUE TITLE
Don't start if not exist settings file

### ISSUE THREAD

**Issue by AlexVRud** [yuriy-budiyev/population#1]
Если нет файла настроек `.population` в домашней директории, то программа не запускается. Падает в

```
mResources = ResourceBundle.getBundle("com.budiyev.population.resource.strings",
                Locale.forLanguageTag(mSettings.get(Settings.LOCALE)));
```
Из-за `null` в результате вызова `mSettings.get(Settings.LOCALE)`

**Comment by yuriy-budiyev** [comment]
Resolved in [b19ad4bc4796c91aea28df2b10913d0a2b37f623](https://github.com/yuriy-budiyev/population/commit/b19ad4bc4796c91aea28df2b10913d0a2b37f623)

**Comment by yuriy-budiyev** [comment]
Added new release: [3.1.2](https://github.com/yuriy-budiyev/population/releases/tag/v3.1.2)
